---
- name: Working with AWS CloudFormation
  hosts: localhost
  become: false
  tasks:
    - name: create a cloudformation stack
      amazon.aws.cloudformation:
        stack_name: "uta-ansible-lab"
        state: "present"
        region: "us-east-1"
        template: "git/aws/cloudformation/uta-ansible-lab.yaml"
        template_parameters:
          KeyPairName: "UTAbastionkeys"
          IAMInstanceProfileName: "uta-ansible-lab"
          NumberOfManagedNodes: 6
